### ISSUE TITLE
Snapshots showing "No preview" for all stories

### ISSUE THREAD

**Issue by adover** [percy/percy-storybook#129]
Versions:
```
    "@percy/storybook": "^3.1.0",
    "@storybook/addon-a11y": "^5.1.9",
    "@storybook/addon-actions": "^5.1.9",
    "@storybook/addon-backgrounds": "^5.1.9",
    "@storybook/addon-centered": "^5.1.9",
    "@storybook/addon-cssresources": "^5.1.9",
    "@storybook/addon-events": "^5.1.9",
    "@storybook/addon-jest": "^5.1.9",
    "@storybook/addon-knobs": "^5.1.9",
    "@storybook/addon-links": "^5.1.9",
    "@storybook/addon-notes": "^5.1.9",
    "@storybook/addon-options": "^5.1.11",
    "@storybook/addon-storyshots": "^5.1.9",
    "@storybook/addon-storysource": "^5.1.11",
    "@storybook/addon-viewport": "^5.1.9",
    "@storybook/addons": "^5.1.11",
    "@storybook/angular": "^5.1.9",
```

Percy finds all relevant stories and snapshots them as expected. However when on the server they all display as no preview. I've run the build server on it's own in a browser and the stories look as expected. 

Running `--debug` returns no errors

**Comment by Robdel12** [comment]
Hey @adover 

Could you reach out via the intercom support bubble on on site? I'd like to get some links to your builds and what not and that's a nice and private way to do that.

**Comment by Robdel12** [comment]
For anyone that lands here via search: There was a storybook error only present when "ejecting" the story (opening it in its isolated iframe, which is what Percy does). 

So, if you're having this issue too, try seeing if there's an error in the JS console on the isolated iframe. If not, please reach out!
