### ISSUE TITLE
Puppeteer requirement

### ISSUE THREAD

**Issue by TimPerry** [percy/percy-storybook#131]
Hey,

I've read through #39 and it sounds like it was a step in the right direction at that time. I have however personally found it painful to have to be dependant on puppeteer just to discover what stories are available(correct me if I am wrong).

Are there any plans to remove this dependency as I feel it lessens the benefits of using a remote service.

Cheers!

**Comment by Robdel12** [comment]
Closing this out now that this SDK no longer relies on Puppeteer (it uses the CLI's Chromium browser used in asset discovery). #301
