### ISSUE TITLE
Percy storybook snapshots are sometimes inconsistent with rendering styled components

### ISSUE THREAD

**Issue by gagandeepgill** [percy/percy-storybook#140]
Sometimes the percy snapshots are missing placeholders/text for our components. We are using next.js to spin up our servers and using emotion for the styled components.

Have any idea why this is happening?

<img width="1894" alt="Screen Shot 2019-09-05 at 11 45 52 AM" src="https://user-images.githubusercontent.com/8551508/64358233-168f0980-cfd4-11e9-8dd6-529ec5093271.png">

<img width="1832" alt="Screen Shot 2019-09-05 at 11 56 21 AM" src="https://user-images.githubusercontent.com/8551508/64358305-36bec880-cfd4-11e9-8c00-b3744f857b7f.png">

**Comment by mackenzie-gray** [comment]
I'm having a very similar issue, it seems to be directly related to the text itself not rendering, but it is also inconsistent? Feels like some sort of race is happening.

We're using `emotion` to build our styled components

<img width="1001" alt="Screen Shot 2019-10-08 at 1 55 56 PM" src="https://user-images.githubusercontent.com/1752970/66420720-664a6180-e9d4-11e9-98e1-ffb57d4993b9.png">
<img width="1096" alt="Screen Shot 2019-10-08 at 1 55 33 PM" src="https://user-images.githubusercontent.com/1752970/66420721-664a6180-e9d4-11e9-956e-8f21eb560c0a.png">

**Comment by samlucax** [comment]
Any updates?

**Comment by zleight1** [comment]
I think this is related to #220

**Comment by pauloabsouto** [comment]
![image](https://user-images.githubusercontent.com/6655747/98379957-b1470600-2026-11eb-9b4e-2944a7c7d2f6.png)

same here

**Comment by Robdel12** [comment]
Could be due to the time it takes to render the component. In v4 of the SDK you can provide waits for when DOM snapshots are captured (only if JS is disabled, which it is by default now in this SDK for these reasons): https://github.com/percy/percy-storybook#storybook-parameters 

Going to close out since now you can wait for the correct state to be captured in the SDK.
