### ISSUE TITLE
Support for addon-contexts

### ISSUE THREAD

**Issue by BPScott** [percy/percy-storybook#146]
Storybook's [addon-contexts](https://github.com/storybookjs/storybook/blob/next/addons/contexts/README.md) is an official plugin that allows users to customize the context their stories are rendered in by allowing customization of a query string parameter in the preview.

For instance you can use it to [choose between themes](https://storybooks-official.netlify.com/?path=/story/addons-contexts--simple-css-theming) - click the last left-aligned icon in the toolbar to change between themes. The preview frame URLs look like https://storybooks-official.netlify.com/iframe.html?id=addons-contexts--simple-css-theming and https://storybooks-official.netlify.com/iframe.html?id=addons-contexts--simple-css-theming&contexts=CSS%20Themes=Desert

If would be very useful if percy could be configured to take screenshots of a single story in multiple context states - by adding configuration to say "for this story run it multiple times with the following set of context parameters". For instance above we could check for visual differences in both the "Ocean" and "Desert" themes in the above example.

---

This is very similar to how percy-storybook offers [rtl support](https://docs.percy.io/docs/storybook#section-rtl-direction-support) - by taking a screenshot with and without the `direction=rtl` parameter, but how that direction parameter is consumed is up to the user.

`addon-contexts` offers a standard way of providing these variations. Standardizing around it would also  remove the need for a dedicated rtl option as instead users would be able to say configure the contexts option with `contexts: ['direction=ltr', 'direction=rtl']` to get both variants.

**Comment by Robdel12** [comment]
I looks like this is now possible with the SDK rewrite in #301 with query params: https://github.com/percy/percy-storybook#storybook-parameters 🎉
