### ISSUE TITLE
Excluding stories?

### ISSUE THREAD

**Issue by brmenchl** [percy/percy-storybook#15]
It would be helpful for `addWithPercyOptions` to allow disabling Percy for a specific story. This would allow us to keep the number of uploaded screenshots down.

**Comment by timhaines** [comment]
@brmenchl I agree - this is a feature I'd like to add.  It would be a good way to skip stories that are designed to be used with a lot of knobs too.  

You're welcome to submit a PR for it to get it started if you like.  Perhaps an option of `'skip': true` ?

**Comment by brmenchl** [comment]
Sounds good. I'll look into it.
