### ISSUE TITLE
Images not showing up in Percy snapshot

### ISSUE THREAD

**Issue by zacktayl** [percy/percy-storybook#153]
I'm seeing this happen where Percy does not always wait for images to load before a snapshot is taken. Is there maybe a way to have percy wait a bit longer? Couldn't find a way to do this natively within Storybook.

### Other Notes
In some of my stories, the images are captured in the snapshot - but in other stories, they are not.

**Comment by Robdel12** [comment]
Hey @zacktayl! Would you be able to reach out via the Intercom support chat? I'd like to take a look at a couple snapshots (this can happen for various reasons)

**Comment by zacktayl** [comment]
Sure thing, @Robdel12! I'm not familiar with the Intercom support chat but I would be available to try it tomorrow if that works for you?

Thanks!

**Comment by Robdel12** [comment]
Hey @zacktayl! Sorry for missing this, no need to schedule a time. 😊 You can send over a message and we'll reply

**Comment by Robdel12** [comment]
I think this was taken care of. Feel free to comment if not! 👍

**Comment by barinbritva** [comment]
What was the solution? I have the same issue now

**Comment by emmasax** [comment]
Would love to know the outcome also.

**Comment by barinbritva** [comment]
@emmasax in my case it was my mistake. I use lazy loading with JavaScript. I solved the issue by disabling lazy loading while components are rendering inside of Storybook. Please check if you have something like that in your components

Another solution could be setting up [`enable-javascript` option](https://docs.percy.io/docs/cli-configuration#snapshot)
