### ISSUE TITLE
No Stories Showing

### ISSUE THREAD

**Issue by code-mattclaffey** [percy/percy-storybook#154]
I am getting no stories rendering when I build storybook. I followed the tutorial and I am wondering if I am missing anything basic because it is the first time I have integrated this.

My example component file would look something like this:
```
import React from 'react';

export default { 
    title: 'Avatar',
    componentSubtitle: 'An avatar component',
    description: 'An avatar component'
};

export const withIcon = () => (
    <div className="c-avatar">
        <i className="c__icon"></i>
    </div>
);
```

My folder output from my build file is:

<img width="410" alt="Screenshot 2019-11-13 at 21 26 30" src="https://user-images.githubusercontent.com/10598938/68805723-47d32800-065c-11ea-891a-3b69925cf261.png">

and this is the output when I run my snapshot command:

"snapshot": "build-storybook -s ./styleguide && percy-storybook --widths=320,740,980,1300 --debug"

outputs:

```
percy-storybook rawStories [] +0ms
percy-storybook selectedStories [] +1ms
percy-storybook found no stories in the static storybook.
```

**Comment by Robdel12** [comment]
Hey @code-mattclaffey! Since you're putting the build output into a different directory (`build-storybook -s ./styleguide`) you'll have to pass the `--build_dir=` flag to `percy-storybook` too. The complete command:

```json
"scripts": {
  "snapshot": "build-storybook -s ./styleguide && percy-storybook --widths=320,740,980,1300 --debug --build_dir=./styleguide"
}
```

**Comment by code-mattclaffey** [comment]
Hello! So I did try that but it still did not work. The -s still renders my static storybook at the root of the project.

**Comment by code-mattclaffey** [comment]
I think the issue is todo with storybook itself. When I build it and access it I have no stories appearing.

**Comment by code-mattclaffey** [comment]
Found the issue it was todo with my configure method. 

```
configure(require.context("../styleguide", true, /\.stories\.jsx$/), module);
configure(
    require.context("../styleguide", true, /\.stories\.(js|mdx)$/),
    module
);
```

If I remove the second one my storybook builds. I was trying to implement mdx files so I can document my components.
