### ISSUE TITLE
Percy + Storybook for React integration - Blank snapshots

### ISSUE THREAD

**Issue by samlucax** [percy/percy-storybook#175]
Hello,

I'm trying to integrate a React Web Applications with Percy.

Locally, I can see the stories normally, but when uploading the screenshot to Percy, it's just a blank white page, like below:

![Screen Shot 2020-02-18 at 18 08 09](https://user-images.githubusercontent.com/11819736/74778367-2d6fa280-527a-11ea-94d3-e582d6772ad6.png)

Can someone help, please?

**Comment by Robdel12** [comment]
Hey @samlucax! When looking at one of your builds there appears to be an error in the isolated story: 
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/2072894/74778818-f8575600-5261-11ea-9694-62543a7dffb2.png">

[You can debug this locally](https://docs.percy.io/docs/storybook#section-debugging-locally) by building storybook and then running a local server within the built output. There are a lot of cases where stories work correctly within the storybook UI but are broken [when isolated](https://user-images.githubusercontent.com/2072894/74779031-63a12800-5262-11ea-9b35-5c22dd7d182c.png).

**Comment by Robdel12** [comment]
Going to close this out -- feel free to comment back if further debugging is needed 👍
