### ISSUE TITLE
Github integration displays all checks have passed when earlier checks havent passed

### ISSUE THREAD

**Issue by BryceLikesDogs** [percy/percy-storybook#177]
I created two lots of screenshots. The first set was unapproved, the second set had no changes.

![Screen Shot 2020-02-24 at 12 58 49 pm](https://user-images.githubusercontent.com/36935978/75124815-b9178200-5705-11ea-96ba-1fed92086346.png)

![Screen Shot 2020-02-24 at 1 02 25 pm](https://user-images.githubusercontent.com/36935978/75125026-0516f680-5707-11ea-8029-b2ddc0f4908f.png)

The github integration shows that all checks have passed, because the second set of screenshots had no changes and therefore passed the checks. But the first set of screenshots wasn't approved and wasn't checked, shouldn't github show the status of the first set instead? It seems as though the unapproved status of the first set of screenshots was overwritten by the second one which had no changes. 

My expectation is that if there are unapproved changes from a earlier build, they should be carried forward until they've been approved or the screenshots are removed. 

Thanks

**Comment by wwilsman** [comment]
Hey @BryceLikesDogs! This doesn't seem like an issue with the Storybook SDK and maybe an issue with the GitHub integration or possibly something else going on. Could you reach out via the support chat on our website with a link to the build?
