### ISSUE TITLE
Failed to launch chrome! [CircleCI]

### ISSUE THREAD

**Issue by mikaarefyev** [percy/percy-storybook#186]
Hey, guys
When running in Circle ci this command "percy storybook" get this error
![image](https://user-images.githubusercontent.com/11503329/76845949-c6c9ae80-6850-11ea-81c4-9650686e80ec.png)
Any help will be appreciated. Using this "@percy/storybook": "^3.3.0"
Thanks!

**Comment by Robdel12** [comment]
Hey @mikaarefyev, thanks for opening an issue! You will need to use a CircleCI image that has the ability to launch a browser. Their `-browser` images are pretty great: `circleci/node:10-browsers`
