### ISSUE TITLE
Snapshotting is broken after updating to the latest version of storybook

### ISSUE THREAD

**Issue by matyas-igor** [percy/percy-storybook#194]
Hello!

We encountered a problem that after updating to the latest version of: storybook, percy/storybook, styled-components and react, our build got completely broken...

![image](https://user-images.githubusercontent.com/3536796/78664671-c911ac80-78d4-11ea-89e1-afb7dbcae260.png)

Maybe you guys have any ideas what could it be?

This was the changes in packages version: 
![image](https://user-images.githubusercontent.com/3536796/78664766-f6f6f100-78d4-11ea-9dd0-26b4a8ee9d0d.png)
![image](https://user-images.githubusercontent.com/3536796/78664841-19890a00-78d5-11ea-84b5-3d7f607c73b5.png)

They're massive but I'd say mostly minimal 😬

**Comment by matyas-igor** [comment]
Another notice - `build-storybook` still works fine, building on Netlify continues work well too. So most likely the issue is in Percy internal headless engine 😬

Submitting screenshots from the local machine gives the same error as in a screenshot above.

**Comment by Robdel12** [comment]
Hey @matyas-igor thanks for opening an issue! Have you tried running the static storybook output locally and viewing an isolated story? https://docs.percy.io/docs/storybook#section-debugging-locally 

Percy is taking the static file output from the build and visiting those stories from the static output (so nothing special). I'd suspect you'll find an error locally when viewing an isolated story

**Comment by wwilsman** [comment]
Another user reported that this error stems from [is-typed-array](https://github.com/inspect-js/is-typed-array). With all the packages that were updated in your screenshot, this transitive dependency might have also been updated causing the issue. You can see which packages rely on it by running the following command:

```sh-session
$ npm ls is-typed-array
```

**Comment by prymitive** [comment]
In my case the problem started with react-popper upgrade that added is-typed-array to dependecies, see [this commit](https://github.com/prymitive/karma/commit/c43459985120d23465ed700152c409ca41e59ef0#diff-d7357f4f94170b80b502203747584f6d). Reverting this commit fixes the issue.
This seems to suggest that is-typed-array checks that are executed when it runs are failing with percy engine.

**Comment by Robdel12** [comment]
Just wanted to call out that there's nothing too special Percy is doing. We take the build output from the static storybook build and then render those isolated stories in our browsers (Chrome &  Firefox). If it's broken in Percy (with an error due to deps), it's probably broken locally too.

**Comment by prymitive** [comment]
Raised inspect-js/is-typed-array#47, could someone with the knowlage of firefox/chrome versions used on percy.io update that ticket with some details? Thanks

**Comment by Robdel12** [comment]
If you're having issues with `Symbol.toStringTag` it sounds like your project is running on _really_ old browsers. Looks like that's been supported since Chrome 49 & Firefox 51. You can upgrade your projects browsers by visiting your projects settings screen. 

The latest versions we're using now is Chrome 78 & Firefox 73.

**Comment by prymitive** [comment]
I did visit project setting and there was a button to upgrade Chrome version, clicked that, reintroduced react-popper 2.1.0 as dependency, that depends on deep-equal, that pulls in is-typed-array, and send new snapshots to percy. Got properly rendered snapshots.
Previous those exact steps were resulting in failing snapshots.
Thanks! Didn't realise that I can upgrade chrome in percy.

**Comment by ljharb** [comment]
I'm confused; neither `BigInt` nor `Symbol` can be polyfilled, so why would `BigInt64Array` exist, but `Symbol.toStringTag` not, even on really ol browsers?

**Comment by Robdel12** [comment]
I ended up cracking open Chrome 67 to step through a debugger with that error. It appears there's a shim being included in the build for symbols

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/2072894/78943014-8391e280-7a80-11ea-98fb-2377cce2a70a.png">

This is what I get when trying to access `Symbol`
<img width="870" alt="image" src="https://user-images.githubusercontent.com/2072894/78943100-b50aae00-7a80-11ea-8d81-008e447f34e2.png">


<img width="730" alt="image" src="https://user-images.githubusercontent.com/2072894/78942802-0a928b00-7a80-11ea-9014-567ac86b3302.png">

**Comment by ljharb** [comment]
In that case, the `symbol.prototype.description` package is just wrapping the already-existing `Symbol`; could you provide the string value of `Symbol` in the last screenshot (like, just prior to `var origSym`)?

**Comment by matyas-igor** [comment]
@Robdel12 yeah, I've tried an isolated story in a static storybook, everything was fine there 😬

@wwilsman and @prymitive thanks for pointing out to `is-typed-array`! Switching to the newer react-popper@2.1.0 removed it from packages and resolved this issue 👍

**Comment by ljharb** [comment]
That’s a shame; is-typed-array/which-typed-array is the only robust mechanism i know of on npm for identifying typed arrays.

The real issue seems to be that the app’s shims are putting the browser in an impossible state. I’d suggest fixing that, so you don’t find yourself with more surprises later.
