### ISSUE TITLE
Feature Request: @storybook/addon-knobs support for access to UI components props

### ISSUE THREAD

**Issue by siggerzz** [percy/percy-storybook#221]
I couldn't see anything around this in the docs, but if this is already implemented, please let me know!

**The Issue**
In Storybook, you can use the [@storybook/addon-knobs](https://www.npmjs.com/package/@storybook/addon-knobs) package to allow you to dynamically change your components prop values within Storybook. In our case, the state of these props can determine the UI for a given component.

It would be great if we could define multiple prop values and have a screenshot for each variant so that we're able to see our UI components in different states.

**Comment by Robdel12** [comment]
I looks like this is now possible with the SDK rewrite in #301 with query params: https://github.com/percy/percy-storybook#storybook-parameters 🎉
