### ISSUE TITLE
Errors in some cases but exits zero

### ISSUE THREAD

**Issue by joscha** [percy/percy-storybook#236]
In some CI builds we see this:

```
[percy] stopping percy...
--
  | [percy] waiting for 3 snapshots to complete...
  | [percy] RequestError Error: read ETIMEDOUT \| Thu Sep 03 2020 00:33:21 GMT+0000 (Coordinated Universal Time)
  | [percy] RequestError: Error: read ETIMEDOUT \| Thu Sep 03 2020 00:33:21 GMT+0000 (Coordinated Universal Time)
  | [percy] done.
  | [percy] finalized build #11111: https://percy.io/XXX/yyy/builds/zzz

```
but `percy-storybook` exits `0` nonetheless. Is there a way we can reflect that either there was a gradual recovery from this error (if this is the case) or exit non-zero in case these errors come up?

**Comment by Robdel12** [comment]
This should no longer be the case now that this SDK is a CLI plugin (#301). 🎉

**Comment by joscha** [comment]
nice! what versions do we need to upgrade in order to get this goodness?

**Comment by Robdel12** [comment]
v4.0.0-beta should do :D https://github.com/percy/percy-storybook/releases/tag/v4.0.0-beta.1

The changes are pretty extensive: https://github.com/percy/percy-storybook#upgrading But this brings the storybook SDK inline with all of our other SDKs _and_ lots of nice new config options (`include`, `exclude`, `queryParams`, etc 😃)

**Comment by Robdel12** [comment]
Oh! Fun thing to note, if you host your storybook somewhere, that can be snapshotted too now. Could be nice if you have the CLI & the storybook plugin installed locally to try out:

```
$ percy storybook https://storybook.foobar.com
```
