### ISSUE TITLE
Update docs for storybook v6

### ISSUE THREAD

**Issue by probablyup** [percy/percy-storybook#245]
https://docs.percy.io/v1/docs/storybook-for-react

v6 uses ESM module exports which seems like a pretty different pattern than what's outlined in the docs

**Comment by Robdel12** [comment]
Hey @probablyup it looks like you're linking to the old v1 docs. These will be the docs you'll want for v5+ of storybook (and I don't think any changes from v5 to v6 will impact how the SDK works -- we're operating off of the static output): https://docs.percy.io/docs/storybook

**Comment by probablyup** [comment]
Ah ok, that's what came up when I googled. Might be worth setting up `rel="canonical"` or something of that nature so Google prefers the newer docs.

**Comment by probablyup** [comment]
@Robdel12 actually looking at those docs you linked, they're the same content. I determined the new pattern would be:

```js
export const StoryName = () => <TestedComponent />

StoryName.parameters = {
  percy: { /* percy options go here */ }
}
```
