### ISSUE TITLE
 "Error: The PERCY_TOKEN environment variable is missing." although it was set

### ISSUE THREAD

**Issue by zurmoehle** [percy/percy-storybook#268]
Hello, I've done everything for the integration with the storybook and added the Environment Variable in the terminal. Nevertheless, when I run "percy-storybook" I get the following error:
`Error: Error: The PERCY_TOKEN environment variable is missing.`

How can I fix this?

**Comment by Robdel12** [comment]
Hey @zurmoehle! How have you confirmed the env var is set? This error will only happen if we can't find `PERCY_TOKEN` set: https://github.com/percy/percy-storybook/blob/e71ee03f05ccf84caa9e1395faa1eec221c8a4e4/src/index.js#L71-L73

Common causes for this if it's not set correctly (powershell vs regular windows command line vs bash) or if you're using a nested docker container. Curious to hear more :)

**Comment by zurmoehle** [comment]
Hey @Robdel12 , thanks for your answer.
I'm working with Mac and the default Terminal. Here i have made `export PERCY_TOKEN=<your token here>` like its described in [https://docs.percy.io/docs/storybook](https://docs.percy.io/docs/storybook)

Or should I set the token at another place?

I'm working wich Storybook in React.
