### ISSUE TITLE
Sanitize log from Percy error

### ISSUE THREAD

**Issue by ljiang-dev** [percy/percy-storybook#300]
When Percy fails with `StatusCodeError: 400`, the logs include the token used to perform the request in clear text. Is there a way to sanitize these logs so that they don't print the token value?

**Comment by Robdel12** [comment]
👋🏼 We're currently [rewriting the SDK to be based on the CLI](https://github.com/percy/percy-storybook/tree/ww/new-cli) Once that's done this shouldn't be an issue anymore

**Comment by joscha** [comment]
Can we fix it in the current implementation? Waiting for the rewrite and then for a fix in the rewritten CLI sounds like it might be a while away. The tokens leak into the logs right now in case there is an error.

**Comment by Robdel12** [comment]
Taken care of now that v4 has been shipped 😃
