### ISSUE TITLE
Prefix CLI Error Messages

### ISSUE THREAD

**Issue by casesandberg** [percy/percy-storybook#31]
This is the current output I am getting with the example code in the docs:
```sh
info @storybook/react v3.4.1
info 
info => Loading custom addons config.
info => Using default webpack setup based on "Create React App".
info Building storybook ...
info Building storybook completed.
No stories were found.
```
I just spent 10 minutes debugging thinking it was a Storybook error only to find that it is indeed an error message from this package.

**Comment by timhaines** [comment]
Thanks @casesandberg - will aim to make this clearer!

**Comment by timhaines** [comment]
Going to `wont-fix` this for now.  May come back to it later.

**Comment by timhaines** [comment]
@casesandberg Have fixed this particular message to be clearer that it's from percy-storybook.  https://github.com/percy/percy-storybook/commit/4caf78d1d15a474ea65b3b89e19d8a0b9a829410
