### ISSUE TITLE
Storybook 6 randomisation support

### ISSUE THREAD

**Issue by wombleton** [percy/percy-storybook#314]
It doesn't seem that the `preview.js` is run before each snapshot in percy. Is there another technique similar to the old [`config.js`](https://github.com/percy/percy-storybook/blob/storybook-for-react-integration-tests%403.1.0/integration-tests/storybook-for-react/storybook/config.js#L12) technique?

**Comment by Robdel12** [comment]
Hey @wombleton! v4.x of the Storybook SDK now takes DOM snapshots by default (with JavaScript _disabled_ in our rendering environment). https://github.com/percy/percy-storybook#unexpected-diffs `inPercy` only works if JS is enabled, so you can enable JavaScript to those snapshots or the whole build to get that functionality back.
