### ISSUE TITLE
(`pnpm`) Error: command storybook not found

### ISSUE THREAD

**Issue by adrianaferrugento** [percy/percy-storybook#377]
## The problem

I've upgraded the @percy/storybook using the following instructions - https://github.com/percy/percy-storybook#upgrading. The command I'm now using to run percy is `percy storybook ./storybook-static` and this is complaining that `command storybook not found`.

## Environment

- Node version: **v14.15.4**
- `@percy/cli` version: **1.0.0-beta.65**
- `@percy/storybook`: **4.0.1**
- OS version: **macOS Big Sur 11.2.1**
- Type of shell command-line [interface]: zsh

## Debug logs
` ›   Error: command storybook not found`

**Comment by Robdel12** [comment]
Hey @adrianaferrugento! Can you tell me more about the steps you took to install? Is the CLI installed globally (highly discouraged)? 

The error is suggesting the storybook CLI plugin can't register with the CLI, likely because they're in different locations

**Comment by adrianaferrugento** [comment]
CLI is not installed globally. I just created a new project using create-react-app and this wasn't an issue there. The only difference between the 2 repos is that I'm using `pnpm` and `webpack5` in my project where I see this error. I have the exact same versions as the create-react-app so I don't understand why I'm seeing this error.

**Comment by Robdel12** [comment]
>  I'm using `pnpm`

Ah, that's the problem here. This is pretty similar to Yarn 2's PnP: https://github.com/percy/cli/issues/295#issuecomment-816170392 We currently don't support non-standard package managers.

**Comment by adrianaferrugento** [comment]
Ah I see, so I'm not going to be able to update this package in a while? Are you going to support it eventually?

**Comment by Robdel12** [comment]
Not likely, it's not supported by dependencies we rely on and it's kind of at odds with how the ecosystem works. If/when it gains mass support across the npm registry, we'll circle back around.
