### ISSUE TITLE
Chrome connection timeouts

### ISSUE THREAD

**Issue by joscha** [percy/percy-storybook#40]
Seeing
```
$ percy-storybook --build_dir=`pwd`/target/storybook --rtl
--
  | Error:  Error: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r564778
  | at Timeout.onTimeout (/var/lib/buildkite-agent/builds/my-org/my-build/web/node_modules/puppeteer/lib/Launcher.js:296:14)
  | at ontimeout (timers.js:466:11)
  | at tryOnTimeout (timers.js:304:5)
  | at Timer.listOnTimeout (timers.js:267:5)
  | error Command failed with exit code 1.
```

in a few builds after upgrading to the puppeteer version from #39.
Maybe we need to tweak the timeouts a bit @timhaines?

**Comment by timhaines** [comment]
@joscha Thanks for reporting this.  I'm surprised to see it.  

It looks like this is a timeout from puppeteer trying to open Chrome/Chromium.  Is it failing intermittently, and succeeding other times on exactly the same CI configuration?  

How are you installing Chrome/Chromium in your CI instance?
Which OS and OS version are you using?

**Comment by joscha** [comment]
It seems to be happening sporadically - I am not really sure what causes it, we didn't change any config lately I think. Chrome/chromium are installed globally, however I thought the puppeteer package downloads it's own version that it uses? OS is Debian Xenial.

**Comment by timhaines** [comment]
Hmm, it's confusing that it's happening sporadically.

I noticed the puppeteer project has a ["not starting on debian"](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch) entry list of dependencies required in their troubleshooting FAQ.  There's also this [giant discussion in an issue](https://github.com/Googlechrome/puppeteer/issues/290).

Neither of those seem to apply to the "works usually, breaks sporadically" scenario though.  Are the machines sometimes do other things in parallel?  They'd have enough memory and resources to open Chrome right?

One thing we can do is add an option, allowing you to specify a [path to the pre-installed Chrome](https://github.com/GoogleChrome/puppeteer#default-runtime-settings).  Let me know if that's something you'd like to explore.

**Comment by joscha** [comment]
> Neither of those seem to apply to the "works usually, breaks sporadically" scenario though. Are the machines sometimes do other things in parallel?

No, they only ever run one job.

> They'd have enough memory and resources to open Chrome right?

Yes, they are more than equipped.

> One thing we can do is add an option, allowing you to specify a path to the pre-installed Chrome. Let me know if that's something you'd like to explore.

Not really. I think the less browser we involve the better :) I'll keep an eye on it and report back here if I find a pattern.

**Comment by timhaines** [comment]
Okay.  Closing this issue for now.  We can re-open if there's more to discuss.  I'd love to hear about it if you do find something.

**Comment by joscha** [comment]
Just saw this again:

```
yarn run v1.7.0
--
  | $ percy-storybook --build_dir=`pwd`/target/storybook --rtl
  | Error:  Error: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r564778
  | at Timeout.onTimeout (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/node_modules/puppeteer/lib/Launcher.js:296:14)
  | at ontimeout (timers.js:466:11)
  | at tryOnTimeout (timers.js:304:5)
  | at Timer.listOnTimeout (timers.js:267:5)
  | error Command failed with exit code 1.
  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
