### ISSUE TITLE
@percy/storybook 1.6.4 does not push all screenshots to percy.io, after downgrade to 1.6.3 started working fine

### ISSUE THREAD

**Issue by rzurawski1337** [percy/percy-storybook#620]
## The problem

I have setup a Percy + Storybook integration last week on Friday (22.07.2022) and after figuring everything out I ran yarn percy storybook with ./storybook-build. Script ran properly, took 6 snapshots of my storybook project, but when I opened the project in percy.io I could see only 2 screenshots to compare.

## Environment

- Node version: 16.15.1
- `@percy/cli` version: 1.6.4
- `@percy/storybook` version: 4.3.1
- OS version: macOS Monterey 12.5
- Type of shell command-line [interface]: macOS

## Details

Took me a couple days to try to figure out what's wrong, especially that there are almost no issues about this integration, so eventually I noticed that both @percy/cli and @percy/storybook had an update 6 days ago so what I actually downloaded was a brand new release. After downgrading to previous versions (1.6.3 and 4.3.0 respectively), and running same percy storybook ./storybook-build command I finally got all of taken screenshots to appear on percy.io

## Debug logs

in my percy storybook --debug log, everything seemed to work, percy went through all pages and handled all screenshots without any errors, warnings or nothing that would seem out of ordinary. I couldn't see any reason why it would upload just two screenshots to percy.io

## Code to reproduce issue

no code here :)

**Comment by wwilsman** [comment]
This should be fixed with [`@percy/cli` v1.7.0](https://github.com/percy/cli/releases/tag/v1.7.0)
