### ISSUE TITLE
No stories found, travis build

### ISSUE THREAD

**Issue by thomaswelton** [percy/percy-storybook#75]
We've recently adopted storybook and now have around 72 stories and are looking to integrate percy with travis.

But we are getting the error `No stories were found.` from percy.

I have built the static storybook locally and opened it to verify that it compiles correctly, and uploading works locally. However when running on travis we get the error above.

I adjusted our storybook config so that it makes only load five stories, and these works fine on Travis.

Are there any known issues with integration or other information we should be aware of?

Travis config
```
language: node_js
node_js:
  - "8.11.1"
cache: yarn
script:
  - yarn build-storybook
  - yarn snapshot
```

**Comment by thomaswelton** [comment]
Ended up running the travis job in debug mode and coping down the compiled stroybook to my local machine. 
Due to a difference in ENV there was JS error running the storybook so was unrelated to percy.

**Comment by cph2117** [comment]
@thomaswelton could you provide a little more detail on the issue? Facing the same thing.

**Comment by thomaswelton** [comment]
Travis has a debug mode that gives you an ssh session. Use that to copy storybook to your local machine (think I used scp)
Then open the compiled storybook locally, you may have some JS errors visible in the console that need fixing
