### ISSUE TITLE
[percy] TypeError: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by alextreppass** [percy/percy-storybook#751]
## The problem

Percy intermittently fails for us with `TypeError: Cannot read properties of undefined`

## Environment

- Node version: 16.4.2
- `@percy/cli` version: 1.25.0
- Version of Percy SDK you’re using (@percy/storybook): 4.3.6
- OS version: Linux (github actions CI runner). Happens very occasionally on OSX locally too
- Type of shell command-line [interface]: bash

## Details

Sometimes, the Percy runner blows up and doesn't take any snapshots. This appears to be due to the 'force stop' code path in the percy cli, from a catch block
```
> [percy] Stopping percy...
> [percy] Build not created
> [percy] TypeError: Cannot read properties of undefined (reading 'message')
```

The type error appears to be due to this line of code in src/utils.js: https://github.com/percy/percy-storybook/blob/bb665fd94c2261e88768d265df66a7742f6006d1/src/utils.js#L128-L130

^ that line assumes that `error` is a defined object, and so causes a TypeError at runtime if `error` isn't an object (e.g is undefined)

## Debug logs

https://gist.github.com/alextreppass/b03b90b90f5447c1f43acba01b2c2100 - these are the `--verbose` logs, unfortunately, Percy isn't giving us much here

## Code to reproduce issue

Cannot reliably reproduce, unfortunately. This happens a few times a day for us on pull request branch CI jobs (Linux)

I have had it happen a small # of times running the command locally (OSX).

What has been helpful is a 'while' loop to re-run percy locally until it fails:

`percy-report.sh`
```bash
yarn percy storybook ./storybook-static --debug
status=$?
[ $status -eq 0 ] && (echo "Percy was successful"; exit 0) || (echo "Percy failed"; exit 1);
```

command to run until it fails:

```bash
while yarn percy:report; do :; done
```

**Comment by alextreppass** [comment]
Update: after further debugging, it seems the error is thrown from the `snapshots.js` catch block here. The error is `undefined` at runtime:

https://github.com/percy/percy-storybook/blob/bb665fd94c2261e88768d265df66a7742f6006d1/src/snapshots.js#L226-L229

**Comment by alextreppass** [comment]
New update: it's failing inside this call here: https://github.com/percy/percy-storybook/blob/bb665fd94c2261e88768d265df66a7742f6006d1/src/snapshots.js#L205

It never gets to the following `yield page.snapshot(options);` instruction

**Comment by itsjwala** [comment]
Thanks for reporting, this is similar to #715 and there are some suggestions mentioned there.
